# espanso configuration file
# Este es el archivo de configuración principal de Espanso.
# Aquí puedes definir opciones globales y atajos de teclado.

# For a complete introduction, visita la documentación oficial en: https://espanso.org/docs/
# Para una introducción completa, visita la documentación oficial en: https://espanso.org/docs/

# You can use this file to define the global configuration options for espanso.
# Puedes usar este archivo para definir las opciones de configuración globales para Espanso.
# These are the parameters that will be used by default on every application,
# Estos son los parámetros que se usarán por defecto en cada aplicación,
# but you can also override them on a per-application basis.
# pero también puedes anularlos por aplicación.

# To make customization easier, this file contains some of the commonly used
# Para facilitar la personalización, este archivo contiene algunos de los parámetros
# de uso común.
# parameters. Feel free to uncomment and tune them to fit your needs!
# ¡Siéntete libre de descomentar y ajustarlos para que se ajusten a tus necesidades!

# --- Toggle key
# Tecla de alternancia

# Customize the key used to disable and enable espanso (when double tapped)
# Personaliza la tecla utilizada para deshabilitar y habilitar Espanso (cuando se toca dos veces)
# Available options: CTRL, SHIFT, ALT, CMD, OFF
# Opciones disponibles: CTRL, SHIFT, ALT, CMD, OFF
# You can also specify the key variant, such as LEFT_CTRL, RIGHT_SHIFT, etc...
# También puedes especificar la variante de la tecla, como LEFT_CTRL, RIGHT_SHIFT, etc...
# toggle_key: ALT
# You can also disable the toggle key completely with
# También puedes deshabilitar la tecla de alternancia por completo con
# toggle_key: OFF

# --- Injection Backend
# Motor de inyección

# Espanso supports multiple ways of injecting text into applications. Each of
# Espanso admite múltiples formas de inyectar texto en las aplicaciones. Cada una
# them has its quirks, therefore you may want to change it if you are having problems.
# de ellas tiene sus peculiaridades, por lo que es posible que desees cambiarlo si tienes problemas.
# By default, espanso uses the "Auto" backend which should work well in most cases,
# Por defecto, Espanso utiliza el backend "Auto" que debería funcionar bien en la mayoría de los casos,
# but you may want to try the "Clipboard" or "Inject" backend in case of issues.
# pero es posible que desees probar el backend "Clipboard" o "Inject" en caso de problemas.
# backend: Clipboard

# --- Auto-restart
# Auto-reinicio

# Enable/disable the config auto-reload after a file change is detected.
# Habilita/deshabilita la recarga automática de la configuración después de que se detecta un cambio de archivo.
# auto_restart: false

# --- Clipboard threshold
# Umbral del portapapeles

# Because injecting long texts char-by-char is a slow operation, espanso automatically
# Debido a que la inyección de textos largos carácter por carácter es una operación lenta,
# Espanso utiliza automáticamente el portapapeles si el texto tiene más de
# uses the clipboard if the text is longer than 'clipboard_threshold' characters.
# 'clipboard_threshold' caracteres.
# clipboard_threshold: 100

# For a list of all the available options, visita la documentación oficial en:
# https://espanso.org/docs/
# Para obtener una lista de todas las opciones disponibles, visita la documentación oficial en: https://espanso.org/docs/
# ::::::::::::Cesar condicional
search_shortcut: ALT+Space
# Atajo de teclado para la búsqueda
disable_x11_fast_inject: true
# Deshabilita la inyección rápida X11 (puede ser necesario en algunos sistemas)

global_vars:
# Variables globales
# Define variables que puedes usar en tus expansiones.
  - name: firstname
    type: echo
    params:
      echo: Jon
  - name: lastname
    type: echo
    params:
      echo: Snow
  - name: comillas
    type: echo
    params:
      echo: "\u0022"
# Define variables globales para nombre, apellido y comillas.